
[tox]
envlist = lint,xlint,py3

[package]
name = skytools
deps =
    psycopg2-binary==2.9.12; platform_python_implementation != 'PyPy'
    setuptools77: setuptools==77.0.3
    setuptools78: setuptools==78.1.1
    setuptools79: setuptools==79.0.1
    setuptools80: setuptools==80.10.2
    setuptools81: setuptools==81.0.0
    setuptools82: setuptools==82.0.1
test_deps =
    coverage==7.14.1
    pytest==9.0.3
    pytest-cov==7.1.0
lint_deps =
    mypy==2.1.0
    pyflakes==3.4.0
    typing-extensions==4.15.0
    types-setuptools==82.0.0.20260518
    types-psycopg2==2.9.21.20260518; platform_python_implementation != 'PyPy'
xlint_deps =
    pylint==4.0.5
doc_deps =
    sphinx==9.1.0
    docutils==0.23

[testenv]
changedir = {toxinidir}
deps =
    {[package]deps}
    {[package]test_deps}
setenv =
    PYTHONDEVMODE=1
    COVERAGE_RCFILE={toxinidir}/.coveragerc
passenv =
    TEST_DB
commands =
    python --version
    pytest \
        --cov \
        --cov-report=term \
        --cov-report=html:{toxinidir}/cover/{envname} \
        --rootdir={toxinidir} \
        {posargs}

[testenv:py3{10,11,12,13,14}-setuptools{77,78,79,80,81,82}]
commands =
    python -c 'import setuptools; print("setuptools: " + setuptools.__version__)'
    python3 setup.py sdist
    python3 setup.py build
    python3 setup.py bdist_wheel

[testenv:lint]
#changedir = {toxinidir}
basepython = python3
deps =
    {[package]deps}
    {[package]lint_deps}
    {[package]test_deps}
commands =
    mypy skytools tests

[testenv:xlint]
#changedir = {envsitepackagesdir}
basepython = python3
deps =
    {[package]deps}
    {[package]test_deps}
    {[package]lint_deps}
    {[package]xlint_deps}
commands =
    pylint skytools

[testenv:docs]
basepython = python3
deps =
    {[package]deps}
    {[package]doc_deps}
changedir = doc
commands = sphinx-build -q -W -b html -d {envtmpdir}/doctrees . ../tmp/dochtml

