#
# https://docs.github.com/en/actions/reference
# https://github.com/actions
#

name: CI

on:
  pull_request: {}
  push: {}

jobs:

  pylint:
    name: "PyLint"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - {PY: "3.10", TOXENV: "lint"}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup Python ${{matrix.test.PY}}"
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.test.PY}}

      - name: "Install tox"
        run: python -m pip -q install tox

      - name: "Test"
        env:
           TOXENV: ${{matrix.test.TOXENV}}
        run: python -m tox -r

  no_database:
    name: "${{matrix.test.osname}} + Python ${{matrix.test.PY}} ${{matrix.test.arch}}"
    runs-on: ${{matrix.test.os}}
    strategy:
      matrix:
        test:
          - {os: "ubuntu-latest", osname: "Linux", PY: "3.7", TOXENV: "py37", arch: "x64"}
          - {os: "ubuntu-latest", osname: "Linux", PY: "3.8", TOXENV: "py38", arch: "x64"}
          - {os: "ubuntu-latest", osname: "Linux", PY: "3.9", TOXENV: "py39", arch: "x64"}
          - {os: "ubuntu-latest", osname: "Linux", PY: "3.10", TOXENV: "py310", arch: "x64"}
          - {os: "macos-latest", osname: "MacOS", PY: "3.10", TOXENV: "py310", arch: "x64"}
          - {os: "windows-latest", osname: "Windows", PY: "3.9", TOXENV: "py39", arch: "x86"}
          - {os: "windows-latest", osname: "Windows", PY: "3.10", TOXENV: "py310", arch: "x64"}
            #- {os: "ubuntu-latest", osname: "Linux", PY: "pypy-3.9", TOXENV: "pypy39", arch: "x64"}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup Python ${{matrix.test.PY}}"
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.test.PY}}
          architecture: ${{matrix.test.arch}}


      - name: "Install tox"
        run: python -m pip -q install tox

      - name: "Build"
        run: python setup.py build

      - name: "Test"
        env:
           TOXENV: ${{matrix.test.TOXENV}}
        run: python -m tox -r -- --color=yes

  database:
    #if: false
    #name: "database test (disabled)"
    name: "PostgreSQL ${{matrix.test.PG}} + Python ${{matrix.test.PY}}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - {PY: "3.10", PG: "14", TOXENV: "py310"}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup Python ${{matrix.test.PY}}"
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.test.PY}}

      - name: "Install tox"
        run: |
          python -m pip -q install tox

      - name: "InstallDB"
        run: |
          echo "::group::apt-get-update"
          echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main ${{matrix.test.PG}}" \
          | sudo tee /etc/apt/sources.list.d/pgdg.list
          sudo -nH apt-get -q update
          echo "::endgroup::"

          echo "::group::apt-get-install"

          # disable new cluster creation
          sudo -nH mkdir -p /etc/postgresql-common/createcluster.d
          echo "create_main_cluster = false" | sudo -nH tee /etc/postgresql-common/createcluster.d/no-main.conf

          sudo -nH apt-get -qyu install postgresql-${{matrix.test.PG}}
          echo "::endgroup::"

          # tune environment
          echo "/usr/lib/postgresql/${{matrix.test.PG}}/bin" >> $GITHUB_PATH
          echo "PGHOST=/tmp" >> $GITHUB_ENV

      - name: "StartDB"
        run: |
          rm -rf data log
          mkdir -p log
          LANG=C initdb data
          sed -ri -e "s,^[# ]*(unix_socket_directories).*,\\1='/tmp'," data/postgresql.conf
          pg_ctl -D data -l log/pg.log start || { cat log/pg.log ; exit 1; }
          sleep 1
          createdb testdb

      - name: "Test"
        env:
          TOXENV: ${{matrix.test.TOXENV}}
          TEST_DB: dbname=testdb host=/tmp
        run: |
          python -m tox -r -- --color=yes

      - name: "StopDB"
        run: |
          pg_ctl -D data stop
          rm -rf data log /tmp/.s.PGSQL*

  cibuildwheel:
    name: "Wheels: ${{matrix.sys.name}}"
    runs-on: ${{matrix.sys.os}}
    strategy:
      matrix:
        sys:
          - {os: "ubuntu-latest", name: "Linux", arches: "auto"}
          - {os: "macos-latest", name: "MacOS", arches: "x86_64 arm64 universal2"}
          - {os: "windows-latest", name: "Windows", arches: "auto"}
    steps:
      - uses: actions/checkout@v3
      - uses: pypa/cibuildwheel@v2.8.0
        env:
          CIBW_ARCHS: ${{matrix.sys.arches}}
      - name: "Check"
        shell: bash
        run: |
          ls -l wheelhouse
      - uses: actions/upload-artifact@v3
        with: {name: "dist", path: "wheelhouse"}

